# Generated by Django 6.0.2 on 2026-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_users_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo_profil',
            field=models.ImageField(blank=True, default='media/defaul_photo_user.png', upload_to='media/'),
        ),
    ]
