# Generated by Django 6.0.2 on 2026-03-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chat_title_friend_friendrequest_togetherchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinchat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
