# Generated by Django 6.0.2 on 2026-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_messageinchat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageinchat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/5d/'),
        ),
    ]
