# Generated by Django 6.0.2 on 2026-03-30 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_friend_created_at_alter_messageinchat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='togetherchat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
