# Generated by Django 6.0.2 on 2026-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_togetherchat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='unaccepted',
            field=models.BooleanField(default=False),
        ),
    ]
