# Generated by Django 6.0.2 on 2026-03-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_friendrequest_unaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='wait',
            field=models.BooleanField(default=True),
        ),
    ]
